language: cpp
compiler: gcc
sudo: require
dist: xenial
 
# whitelist
branches:
  only:
    - c++-version
    - test_travis
    - /v\d+\.\d+[a-z]/
    - /v\d+\.\d+\.\d+[a-z]/
    - /v\d+\.\d+\.\d+/
    - /v\d+\..+/
    
before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install qt5-qmake

  
install:
  - sudo apt-get -y install kio-dev

before_script:
  - cmake --version
  - export QT_SELECT=qt5
  - qmake -v
  
script:
  - cd src
  - qmake CONFIG+=release DawnlightSearch.pro
  - make -j$(nproc)
  - make clean
    
    
  - install -D dawnlightsearch ./../AppDir/usr/bin/dawnlightsearch
  - install -d  ./../AppDir/usr/lib
  - install -D dawnlightsearch_appimage.desktop ./../AppDir/usr/share/applications/dawnlightsearch.desktop
  - install -D  ./ui/icon/main.png  ./../AppDir/usr/share/icons/hicolor/255/dawnlightsearch.png
  - install -D /bin/lsblk ./../AppDir/usr/bin/lsblk
# seems -extra-plugins=sqldrivers,sqldrivers/libqsqlite.so does not work
  - install -D /usr/lib/x86_64-linux-gnu/qt5/plugins/sqldrivers/libqsqlite.so ./../AppDir/usr/lib/libqsqlite.so
  - locate sqldrivers/libqsqlite.so
#  - install -D $(locate sqldrivers/libqsqlite.so | grep qt5) ./../AppDir/usr/lib/libqsqlite.so
  - cd ..
  - wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
  - chmod +x linuxdeployqt-continuous-x86_64.AppImage
  - export QT_SELECT=qt5
  - qmake -v
#  - export VERSION=$(git rev-parse --short HEAD) # linuxdeployqt uses this for naming the file
  - export VERSION=$(cat src/VERSION) # linuxdeployqt uses this for naming the file
  - ./linuxdeployqt-continuous-x86_64.AppImage ./AppDir/usr/bin/dawnlightsearch  -always-overwrite -bundle-non-qt-libs -extra-plugins=sqldrivers,sqldrivers/libqsqlite.so
  - ./linuxdeployqt-continuous-x86_64.AppImage ./AppDir/usr/share/applications/dawnlightsearch.desktop  -always-overwrite -appimage

before_deploy:
  - mv ./src/dawnlightsearch DawnlightSearch_v$(cat src/VERSION)
  - sha256sum DawnlightSearch* > DawnlightSearch.sha256
  - ls
  
deploy:
  provider: releases
  api_key:
    secure: lX2004eoeJkx5ZVCk9bhqexNZ9wWpn7veJc0DBV1xCDdJkmSQlRX4u+3ariAPtG99iGCaqrWqBr7DJShHxfpx/zdJAAZPbNVy+VEPrS3PFg3cNsGpA58jMVWC7fX9imo91r6X53yWA4u+smXaYPbwZ3PrhaDTy8mqRyqqB2M8TLAIstq2Dg+/ricg9GK0Qdefm74GiVXvrTF1i9aGCJkYFVb8WNnTizNGZwVCwwialTvZNykaNiVUMWSNS3djKZD3Fl/T9XpNR+qmSy4gUGhOoL+de7wrhfNpJNjKJ1a4xeAk4o/NBxZZ0JrRztKCkaooqVkZ+UVUk+pVFSj3RKankmU39hjR+ipVmduS5MGmRLSsJt2FgSgkomu4/uRxcu9rdbe7bjjj92E6ka+BQcs0qLXKGKNcTL90t7XBAUZVDAktYFlrEy4wiiXCpHGDUsFR7Xy1PZ69cLwZbgX4/D4t1XfwWJ+URaDNTgUcYrNql+VOZBpbTYMVw22Hfl7nRa13GjZqsJIpXHynTrTMub6MfYXbrF8MaSz9QndE21eac9IUivWxtcwdNZUpCUTA8+3Wi2h0s7Es7lEUzJmPsw9jTvL3lNSQGfZQ/xFOxYiIHmf1PBEOBCjsDwFaA+lsPmcyGY3iaQdiD/TIH1pjpP8zWaa3xIotuonntdxM96mb3c=
    #$MY_GITHUB_SECURE_KEY_TOKEN
  file_glob: true
  file:
    - DawnlightSearch*
  skip_cleanup: true
  on:
    tags: true
    repo: chg-hou/DawnlightSearch
    branch: c++-version
