language: cpp
compiler: gcc
sudo: require
dist: xenial
 
# whitelist
branches:
  only:
    - c++-version
    - test_travis

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install qt5-qmake

  
install:
  - sudo apt-get -y install kio-dev

before_script:
  - cmake --version
  - export QT_SELECT=qt5
  - qmake -v
  
script:
  - cd src
  - qmake CONFIG+=release DawnlightSearch.pro
  - make -j$(nproc)
  - make clean
    
    
  - install -D dawnlightsearch ./../AppDir/usr/bin/dawnlightsearch
  - install -d  ./../AppDir/usr/lib
  - install -D dawnlightsearch_appimage.desktop ./../AppDir/usr/share/applications/dawnlightsearch.desktop
  - install -D  ./ui/icon/main.png  ./../AppDir/usr/share/icons/hicolor/255/dawnlightsearch.png
  - install -D /bin/lsblk ./../AppDir/usr/bin/lsblk
  - cd ..
  - wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
  - chmod +x linuxdeployqt-continuous-x86_64.AppImage
  - export QT_SELECT=qt5
  - qmake -v
  - git rev-parse --short HEAD
  - export VERSION=$(git rev-parse --short HEAD) # linuxdeployqt uses this for naming the file
  - ./linuxdeployqt-continuous-x86_64.AppImage ./AppDir/usr/bin/dawnlightsearch  -always-overwrite -bundle-non-qt-libs -extra-plugins=qsqlite
  - ./linuxdeployqt-continuous-x86_64.AppImage ./AppDir/usr/share/applications/dawnlightsearch.desktop  -always-overwrite -appimage
