language: cpp
compiler: gcc
sudo: require
dist: xenial
 
# whitelist
branches:
  only:
    - c++-version
    - test_travis

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install qt5-qmake

  
install:
  - sudo apt-get -y install kio-dev

before_script:
  - cmake --version
  - export QT_SELECT=qt5
  - qmake -v
  
script:
  - cd src
  - qmake CONFIG+=release DawnlightSearch.pro
  - make -j$(nproc)
  - make clean
